### PR TITLE
Add template with no Makefile for using with wash build

### PR DESCRIPTION
**Pull request by jordan-rash**
Template without Makefile for `wash build` testing.

Signed-off-by: Jordan Rash <15827604+jordan-rash@users.noreply.github.com>

### CODE REVIEW

**Comment by jordan-rash** [comment]
Locally....
```bash
╰─❯ wash new actor -p /tmp/project-templates/actor/hello_world
🤷   Project Name : test
🔧   Generating template ...
[ 1/14]   Done: .cargo/config.toml
[ 7/14]   Done: .gitignore
[ 8/14]   Done: Cargo.lock
[ 9/14]   Done: Cargo.toml
[10/14]   Done: README.md
[11/14]   Done: project-generate.toml
[12/14]   Done: src/lib.rs
✨   Done! New project created /Users/jordan/Library/Mobile Documents/com~apple~CloudDocs/github/cosmonic/things-to-build/petclinic/test

╰─❯ cd test

╰─❯ wash build
Building actor...
    Updating crates.io index
   Compiling proc-macro2 v1.0.43
   Compiling quote v1.0.21
<..SNIP..>
    Finished release [optimized] target(s) in 47.24s
Done building actor
Signing actor...
No keypair found in "/Users/jordan/.wash/keys/test_module.nk".
                    We will generate one for you and place it there.
                    If you'd like to use alternative keys, you can supply them as a flag.


Successfully signed build/test_s.wasm with capabilities: wasmcloud:httpserver
```

**Review by autodidaddict — APPROVED** [review]

**Review by brooksmtownsend — COMMENTED** [review]
This is all in service with not including the Makefile, right? I would say we should just make (heh) the switch to no Makefile after wash `0.14.0` or so and not worry about creating a whole new template. I'm pretty sure that this is just to keep the actor projects clean and I wouldn't want users to choose between Makefile hello world or no-makefile

**Comment by thomastaylor312** [comment]
Agree with Brooks here. I don't want users to have to choose between the two

**Comment by brooksmtownsend** [comment]
@jordan-rash I think I'm going to close this PR, but would love to remove the Makefiles from the current templates now that `wash build` has more robust support for building

**Comment by jordan-rash** [comment]
I agree 👍🏼

**Pull request closed without merging**
