### PR TITLE
Monorepo Actor Discovery

### PR DESCRIPTION
**Pull request by stephenandary**
The monorepo actor has several ways forward based on my investigation over the last few days. I will lay out some of my thoughts 
 about what I was trying to achieve to get input so I can help produce a template acceptable for WASMcloud users, as well as myself. 
 
I see 2 ways forward when it comes to the template: 
1.  Modify the existing template workflows so that a user can make slight modifications to work with a monorepo
2.  Create a separate actor template for monorepos
I have been looking into the first option, but I am considering trying the second option instead - it would be good to align here. 

The next thing I think is very important to address for a monorepo template is how to make it most efficient when it comes to maintenance and triggering releases. I also see 2 ways forward here (though I am still ignorant to GH actions):
1.  Have 1 workflow for each actor/provider/interface (I see myself having separate repos for actors, providers, and interfaces)
2.  Having 1 workflow which can handle all project directories 
Again, I have been investigating option 1, though I have been trying to work towards option 2 as I learn. I personally think option 2 would be better here, but input would be really helpful. 

What I am currently considering, and would like to try: 
- Creating a separate template specific to monorepo actors to make the workflow less complex; requiring logic to handle multiple scenarios adds additional complexity which I think is detrimental. 
- Using a tag to extract the actor name so that a single workflow can be used for all actors
Where I think this is problematic: 
- This is related to release-only workflow, have not considered how this affects building actors for non-release, though I imagine I can just use `Wash build` in the directory

Again, really grateful for the help, and hope the above makes sense.

### CODE REVIEW

**Comment by stephenandary** [comment]
I also apologize, I tried redoing this PR so there were not so many files in it (I have not worked with forked repos before), but failed lol. The only file to look at here is the release.yml file in the monorepo-actor at the moment.

**Comment by stephenandary** [comment]
@brooksmtownsend, I would like to start trying to work on the method I am currently considering now, when will it be possible for me to align with you so that I can understand if I need to remove the makefiles for `wash build`?

**Comment by brooksmtownsend** [comment]
@stephenandary I can just review the release file and then we can work on creating a different branch or removing some of the files, going to have to break out some git-fu 😄 

As far as the method you're using, what we should do to start is keep the Makefile but replace instances of `make` with `wash build`. The Makefile will be deprecated, but shouldn't be removed quite yet until `wash build` can fully replace its options and features

**Comment by stephenandary** [comment]
I will close this when I have something working in my new branch, then hopefully we avoid git-fu haha. I have moved the release up to .github/workflows at root level, and renamed it monorepo_actor_release, deleted the monorepo-actor as I don't a template directory is really necessary if people just copy that new workflow, and have added .devcontainer to .gitignore so hopefully the new branch is much more clean.

**Comment by stephenandary** [comment]
Closing to create more clean PR

**Pull request closed without merging**
